stages:
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification:
  recipients:
  - recipient: '@Luiz'
    notifier: c-jmn6q:n-ptpv8
  condition:
  - Success
  - Failed
